const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const KEY = 'fivefold-arc:appearance-studio'; let developerKey = sessionStorage.getItem('fivefold-arc:developer-key') || '';
window.addEventListener('message', event => {
  if (event.origin === location.origin && event.data?.type === 'fivefold-arc:appearance-preview-ready') renderExactPreview();
});
const icons = { life: '♥', commander: '♜', radiation: '☢', poison: '☠', energy: 'ϟ', generic: '◇' };
const labels = { life: 'Life', commander: 'Commander damage', radiation: 'Radiation', poison: 'Poison', energy: 'Energy', generic: 'Generic counters' };
const neutral = { id: 'neutral', name: 'Neutral Arc', status: 'Approved', edited: 'Built in', background: '#080808', surface: '#161616', accent: '#d8ae61', secondary: '#70a97a', text: '#f4ecd9', muted: '#afa590', atmosphere: 'dark', atmosphereColor: '#70a97a', atmosphereStrength: 35, atmospherePosition: 'top', backgroundTreatment: 'plain', backgroundAsset: '', backgroundScale: 100, backgroundPositionX: 50, backgroundPositionY: 50, ring: 'arc', sealAsset: '', buttonTreatment: 'glass', buttonOpacity: 100, buttonBlur: 0, buttonBorder: 70, lifeButtonOpacity: 100, lifeButtonBlur: 0, lifeButtonBorder: 70, customLifeOpacity: 100, customLifeBlur: 0, customLifeBorder: 70, commanderTaxOpacity: 100, commanderTaxBlur: 0, commanderTaxBorder: 70, seatTreatment: 'raised', seatOpacity: 100, seatBlur: 0, seatBorder: 70, symbols: { ...icons }, symbolAssets: {}, symbolScale: {} };
let store; try { store = JSON.parse(localStorage.getItem(KEY)) || { skins: [neutral], selected: 'neutral' }; } catch { store = { skins: [neutral], selected: 'neutral' }; }
if (!store.skins?.some(s => s.id === 'neutral')) store.skins.unshift(neutral);
store.assets ||= []; store.skins.forEach(normalizeSkin);
let selectedId = store.selected || 'neutral', draft = null, original = null, previewSize = 'phone', previewState = 'turn', previewMode = 'life', previewModeIndex = 0, previewPlayers = 4, showingBaseline = false;
const fields = ['name','background','surface','accent','secondary','text','muted','atmosphere','atmosphereColor','atmosphereStrength','atmospherePosition','backgroundTreatment','backgroundScale','backgroundPositionX','backgroundPositionY','ring','sealAsset','buttonTreatment','buttonOpacity','buttonBlur','buttonBorder','lifeButtonOpacity','lifeButtonBlur','lifeButtonBorder','customLifeOpacity','customLifeBlur','customLifeBorder','commanderTaxOpacity','commanderTaxBlur','commanderTaxBorder','seatTreatment','seatOpacity','seatBlur','seatBorder'];
function normalizeSkin(skin) { skin.backgroundAsset ||= ''; skin.sealAsset ||= ''; skin.symbolAssets ||= {}; skin.symbolScale ||= {}; skin.atmosphereColor ||= skin.secondary || '#70a97a'; skin.atmosphereStrength = Math.min(80, Math.max(0, Number(skin.atmosphereStrength) || 35)); skin.atmospherePosition ||= 'top'; skin.backgroundScale = Math.min(200, Math.max(50, Number(skin.backgroundScale) || 100)); skin.backgroundPositionX = Math.min(100, Math.max(0, Number(skin.backgroundPositionX) || 50)); skin.backgroundPositionY = Math.min(100, Math.max(0, Number(skin.backgroundPositionY) || 50)); ['button','lifeButton','customLife','commanderTax','seat'].forEach(prefix => { skin[`${prefix}Opacity`] = Math.min(100, Math.max(35, Number(skin[`${prefix}Opacity`]) || 100)); skin[`${prefix}Blur`] = Math.min(16, Math.max(0, Number(skin[`${prefix}Blur`]) || 0)); skin[`${prefix}Border`] = Math.min(100, Math.max(0, Number.isFinite(Number(skin[`${prefix}Border`])) ? Number(skin[`${prefix}Border`]) : 70)); }); }
function saveStore() { try { if (location.protocol !== 'file:') { localStorage.removeItem(KEY); return true; } localStorage.setItem(KEY, JSON.stringify(store)); } catch { /* direct-file cache is optional */ } return true; }
const catalogHeaders = { 'content-type': 'application/json', 'x-feedback-portal-key': developerKey };
async function saveCatalog() { try { for (const asset of store.assets.filter(item => item.data)) { const response = await fetch(`/api/appearance-studio/assets/${asset.id}`, { method: 'PUT', headers: catalogHeaders, body: JSON.stringify(asset) }); if (!response.ok) throw new Error(); } const catalog = { ...store, assets: store.assets.map(({ data, ...asset }) => asset) }; const response = await fetch('/api/appearance-studio/catalog', { method: 'PUT', headers: catalogHeaders, body: JSON.stringify(catalog) }); if (!response.ok) throw new Error(); return true; } catch { toast('Open Appearance Studio from the protected Developer Assets tab to save this catalog.'); return false; } }
async function loadAssetData(asset) { if (asset.data) return asset; const response = await fetch(`/api/appearance-studio/assets/${asset.id}`, { headers: { 'x-feedback-portal-key': developerKey } }); if (!response.ok) throw new Error(); return (await response.json()).asset; }
function selected() { return store.skins.find(s => s.id === selectedId) || neutral; }
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function relativeDate() { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date()); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => el.hidden = true, 2600); }
function setSaveState(text = 'Unsaved') { $('#saveState').textContent = text; }
function renderLibrary() { const query = $('#skinSearch').value.trim().toLowerCase(); $('#skinLibrary').innerHTML = store.skins.filter(s => s.name.toLowerCase().includes(query)).map(s => `<button class="skin-card ${s.id === selectedId ? 'selected' : ''}" data-skin="${s.id}" type="button"><span class="skin-thumb" style="--thumb-bg:${s.background};--thumb-accent:${s.accent}"></span><span><strong>${escape(s.name)}</strong><small>${s.status} · ${s.edited}</small></span></button>`).join('') || '<p class="empty">No skins match.</p>'; $$('#skinLibrary [data-skin]').forEach(b => b.addEventListener('click', () => selectSkin(b.dataset.skin)));
}
function escape(s) { return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function assetsFor(placement) { return store.assets.filter(asset => asset.placement === placement); }
function assetOptions(placement, value, empty) { return `<option value="">${empty}</option>${assetsFor(placement).map(asset => `<option value="${asset.id}" ${asset.id === value ? 'selected' : ''}>${escape(asset.name)}</option>`).join('')}`; }
function renderSymbols() { $('#symbolControls').innerHTML = Object.entries(labels).map(([key, label]) => `<div class="symbol-control"><span>${label}<small>Accessible label fixed</small></span><select data-symbol="${key}" aria-label="${label} built-in symbol">${Object.values(icons).map(symbol => `<option value="${symbol}" ${draft.symbols[key] === symbol ? 'selected' : ''}>${symbol}</option>`).join('')}</select><select data-symbol-asset="${key}" aria-label="${label} custom image">${assetOptions('symbol', draft.symbolAssets[key], 'Built-in symbol')}</select><label class="icon-scale">Icon scale <output>${draft.symbolScale[key] || 100}%</output><input data-symbol-scale="${key}" aria-label="${label} icon scale" type="range" min="60" max="200" step="5" value="${draft.symbolScale[key] || 100}"></label><button class="text-button" data-symbol-autofit="${key}" type="button">Auto-fit icon</button></div>`).join(''); $$('#symbolControls select[data-symbol]').forEach(el => el.addEventListener('input', () => { draft.symbols[el.dataset.symbol] = el.value; changed(); })); $$('#symbolControls select[data-symbol-asset]').forEach(el => el.addEventListener('input', () => { draft.symbolAssets[el.dataset.symbolAsset] = el.value; changed(); })); $$('#symbolControls input[data-symbol-scale]').forEach(el => el.addEventListener('input', () => { draft.symbolScale[el.dataset.symbolScale] = Number(el.value); el.previousElementSibling.textContent = `${el.value}%`; changed(); })); $$('#symbolControls [data-symbol-autofit]').forEach(button => button.addEventListener('click', () => { const key = button.dataset.symbolAutofit; draft.symbolScale[key] = 100; renderEditor(); changed(); })); }
function renderAssets() { $('#backgroundAsset').innerHTML = assetOptions('background', draft.backgroundAsset, 'No imported art'); $('#sealAsset').innerHTML = assetOptions('symbol', draft.sealAsset, 'Built-in seal'); $('#assetLibrary').innerHTML = store.assets.length ? store.assets.map(asset => `<div><b>${escape(asset.name)}</b><small>${asset.placement} · ${escape(asset.source)}</small><button type="button" class="text-button" data-delete-asset="${asset.id}">Delete</button></div>`).join('') : '<p class="helper">No imported assets yet.</p>'; $$('[data-delete-asset]').forEach(button => button.addEventListener('click', () => deleteAsset(button.dataset.deleteAsset))); }
function clearAssetReference(skin, id) { if (!skin) return; if (skin.backgroundAsset === id) skin.backgroundAsset = ''; if (skin.sealAsset === id) skin.sealAsset = ''; Object.keys(skin.symbolAssets || {}).forEach(key => { if (skin.symbolAssets[key] === id) skin.symbolAssets[key] = ''; }); }
async function deleteAsset(id) { const asset = store.assets.find(item => item.id === id); if (!asset || !confirm(`Delete “${asset.name}” from the asset library? This cannot be undone.`)) return; const previousStore = clone(store), previousDraft = clone(draft), previousOriginal = clone(original); store.assets = store.assets.filter(item => item.id !== id); store.skins.forEach(skin => clearAssetReference(skin, id)); clearAssetReference(draft, id); clearAssetReference(original, id); if (!await saveCatalog()) { store = previousStore; draft = previousDraft; original = previousOriginal; renderEditor(); renderPreview(); return; } saveStore(); renderEditor(); renderPreview(); validate(); setSaveState('Asset deleted'); toast(`${asset.name} deleted from the server catalog.`); }
function renderEditor() { fields.forEach(key => { const el = $(`#${key === 'name' ? 'skinName' : key}`); if (el) el.value = draft[key]; }); $('#atmosphereStrengthValue').textContent = `${draft.atmosphereStrength}%`; $('#backgroundScaleValue').textContent = `${draft.backgroundScale}%`; $('#backgroundPositionXValue').textContent = `${draft.backgroundPositionX}%`; $('#backgroundPositionYValue').textContent = `${draft.backgroundPositionY}%`; ['button','lifeButton','customLife','commanderTax','seat'].forEach(prefix => { $(`#${prefix}OpacityValue`).textContent = `${draft[`${prefix}Opacity`]}%`; $(`#${prefix}BlurValue`).textContent = `${draft[`${prefix}Blur`]}px`; $(`#${prefix}BorderValue`).textContent = `${draft[`${prefix}Border`]}%`; }); $('#skinNameLabel').textContent = draft.name; renderAssets(); renderSymbols(); constrainIconScales(); }
function constrainIconScales() { $$('#symbolControls input[data-symbol-scale]').forEach(el => { const value = Math.min(200, Math.max(60, Number(el.value) || 100)); el.value = String(value); draft.symbolScale[el.dataset.symbolScale] = value; const output = el.parentElement?.querySelector('output'); if (output) output.textContent = `${value}%`; }); }
function selectSkin(id) { selectedId = id; store.selected = id; original = clone(selected()); draft = clone(selected()); renderLibrary(); renderEditor(); renderPreview(); validate(); saveStore(); setSaveState(draft.status === 'Approved' ? 'Approved' : 'Saved'); }
function changed() { $('#skinNameLabel').textContent = draft.name || 'Untitled skin'; renderPreview(); validate(); setSaveState('Unsaved'); }
function contrast(a, b) { const lum = hex => { const c = hex.replace('#','').match(/.{2}/g).map(v => parseInt(v,16)/255).map(v => v <= .03928 ? v/12.92 : ((v+.055)/1.055) ** 2.4); return .2126*c[0]+.7152*c[1]+.0722*c[2]; }; const [x,y] = [lum(a),lum(b)].sort((m,n) => n-m); return (x+.05)/(y+.05); }
function validate() { const checks = [
  { label: 'Life total is legible over its counter surface', pass: contrast(draft.text, draft.surface) >= 4.5, screen: 'Your turn · life total' },
  { label: 'Player and seat label remain distinct from life total', pass: contrast(draft.muted, draft.surface) >= 3, screen: 'Your turn · ownership' },
  { label: 'Turn label and End Turn control remain visible', pass: contrast(draft.text, draft.background) >= 4.5 && contrast(draft.accent, draft.background) >= 3, screen: 'Your turn · turn action' },
  { label: 'Artwork keeps controls readable', pass: !draft.backgroundAsset, advisory: true, screen: draft.backgroundAsset ? 'Needs visual review with imported art' : 'No imported art selected' },
  { label: 'Active turn is labeled, not color-only', pass: true, screen: 'Your turn / another turn' },
  { label: 'Connection state has an icon and label', pass: true, screen: 'Disconnected view' },
  { label: 'Labels fit at 320 × 700', pass: draft.name.length <= 32, screen: 'Compact phone' },
  { label: 'Preview touch targets are at least 44 px', pass: false, advisory: true, screen: 'Needs a real phone check' }
]; const failed = checks.filter(c => !c.pass && !c.advisory); const advisory = checks.filter(c => !c.pass && c.advisory); $('#validationSummary').textContent = failed.length ? `${failed.length} required check${failed.length > 1 ? 's' : ''} need attention.` : advisory.length ? `${advisory.length} visual check${advisory.length > 1 ? 's' : ''} still need review.` : 'All required gameplay readability checks pass.'; $('#validationSummary').className = `validation-summary ${failed.length ? 'fail' : advisory.length ? 'review' : 'pass'}`; $('#validationList').innerHTML = checks.map(c => `<li class="${c.pass ? 'pass' : c.advisory ? 'review' : 'fail'}"><span>${c.pass ? '✓' : '!'}</span><div><strong>${c.label}</strong><small>${c.screen}</small></div></li>`).join(''); return !failed.length; }
function renderPreview() { const skin = showingBaseline ? neutral : draft; const root = $('#previewScreen'); root.style.setProperty('--bg', skin.background); root.style.setProperty('--surface', skin.surface); root.style.setProperty('--accent', skin.accent); root.style.setProperty('--secondary', skin.secondary); root.style.setProperty('--text', skin.text); root.style.setProperty('--muted', skin.muted); root.style.setProperty('--seat-opacity', skin.seatOpacity); root.style.setProperty('--seat-blur', skin.seatBlur); root.style.setProperty('--seat-border', skin.seatBorder); root.dataset.art = skin.backgroundTreatment; root.dataset.button = skin.buttonTreatment; root.dataset.seat = skin.seatTreatment; root.dataset.atmosphere = skin.atmosphere; $('#previewRing').textContent = skin.ring === 'none' ? '' : skin.ring === 'orbit' ? '◎' : '◇'; $('#previewRing').dataset.ring = skin.ring; const keys = Object.keys(icons), key = keys[previewModeIndex], values = [40, 16, 3, 2, 7, 4], data = previewState === 'damage' ? [['MIRA', 40], ['JORI', 16], ['BEA', 32], ['NOX', 27]] : [['MIRA', 40], ['JORI', 38], ['BEA', 31], ['NOX', 40]]; $('#previewSeats').innerHTML = data.map(([name, life], i) => `<div class="${i === 0 ? 'active' : ''}"><small>${name}</small><strong>${life}</strong></div>`).join(''); const other = previewState === 'other', offline = previewState === 'offline', damage = previewState === 'damage'; $('#previewOffline').hidden = !offline; $('#previewTurnLabel').textContent = other ? "JORI'S TURN" : 'YOUR TURN'; $('#previewTurnPlayer').textContent = other ? 'JORI' : 'MIRA'; $('#previewMode').textContent = damage ? 'COMMANDER DAMAGE' : labels[key].toUpperCase(); $('#previewCounter output').textContent = damage ? '16' : values[previewModeIndex]; $('#previewEndTurn').textContent = other ? 'Waiting for Jori' : 'End turn → Next player'; $('#previewEndTurn').disabled = other || offline; $('#phonePreview').className = `phone-preview size-${previewSize}`; $('#previewButton').textContent = showingBaseline ? 'Show draft' : 'Show baseline'; $('#compareNote').innerHTML = showingBaseline ? 'Viewing the <strong>Neutral Arc baseline</strong>. Choose “Show draft” to return to your unsaved changes.' : 'Editing against <strong>Neutral Arc</strong>. Preview content is representative only; no table data is connected.'; applyImportedArt(skin); applyAtmosphere(skin); applyButtonControls(skin); renderExactPreview(); }
async function saveDraft() { const previousStore = clone(store); draft.name = draft.name.trim() || 'Untitled skin'; const i = store.skins.findIndex(s => s.id === selectedId); store.skins[i] = { ...clone(draft), id: selectedId, status: draft.status === 'Approved' ? 'Approved' : 'Draft', edited: relativeDate() }; if (!await saveCatalog()) { store = previousStore; return; } original = clone(store.skins[i]); saveStore(); renderLibrary(); renderEditor(); setSaveState('Saved draft'); toast('Draft saved to the developer catalog.'); }
async function duplicate() { const previousStore = clone(store), id = `skin-${Date.now()}`; const copy = { ...clone(draft), id, name: `${draft.name || 'Untitled'} copy`, status: 'Draft', edited: relativeDate() }; store.skins.unshift(copy); selectedId = id; store.selected = id; if (!await saveCatalog()) { store = previousStore; selectedId = previousStore.selected || 'neutral'; return; } saveStore(); selectSkin(id); toast('Draft duplicated.'); }
async function publish() { if (!validate()) return toast('Resolve required readability checks before publishing.'); await saveDraft(); const skin = store.skins.find(s => s.id === selectedId); if (!skin) return; const previousStore = clone(store); skin.status = 'Approved'; skin.edited = relativeDate(); draft.status = 'Approved'; if (!await saveCatalog()) { store = previousStore; return; } original = clone(skin); saveStore(); renderLibrary(); setSaveState('Approved'); toast('Skin approved in the developer catalog.'); }
fields.forEach(key => { const el = $(`#${key === 'name' ? 'skinName' : key}`); el.addEventListener('input', () => { draft[key] = ['atmosphereStrength', 'backgroundScale', 'backgroundPositionX', 'backgroundPositionY', 'seatOpacity', 'seatBlur', 'seatBorder'].includes(key) ? Number(el.value) : el.value; if (key === 'atmosphereStrength') $('#atmosphereStrengthValue').textContent = `${el.value}%`; if (key === 'backgroundScale') $('#backgroundScaleValue').textContent = `${el.value}%`; if (key === 'backgroundPositionX') $('#backgroundPositionXValue').textContent = `${el.value}%`; if (key === 'backgroundPositionY') $('#backgroundPositionYValue').textContent = `${el.value}%`; if (key === 'seatOpacity') $('#seatOpacityValue').textContent = `${el.value}%`; if (key === 'seatBlur') $('#seatBlurValue').textContent = `${el.value}px`; if (key === 'seatBorder') $('#seatBorderValue').textContent = `${el.value}%`; changed(); }); });
$('#skinSearch').addEventListener('input', renderLibrary); $('#newSkinButton').addEventListener('click', () => { const id = `skin-${Date.now()}`; store.skins.unshift({ ...clone(neutral), id, name: 'Untitled skin', status: 'Draft', edited: relativeDate() }); selectedId = id; selectSkin(id); }); $('#saveButton').addEventListener('click', saveDraft); $('#duplicateButton').addEventListener('click', duplicate); $('#publishButton').addEventListener('click', publish); $('#revertButton').addEventListener('click', () => { draft = clone(original); renderEditor(); renderPreview(); validate(); setSaveState('Reverted'); }); $('#previewButton').addEventListener('click', () => { showingBaseline = !showingBaseline; renderPreview(); }); $('#previewEndTurn').addEventListener('click', () => { previewState = 'other'; $$('[data-state]').forEach(x => x.classList.toggle('selected', x.dataset.state === 'other')); renderPreview(); }); $$('.preview-nav button').forEach((button, index) => button.addEventListener('click', () => { previewModeIndex = index; renderPreview(); }));
$$('[data-size]').forEach(b => b.addEventListener('click', () => { previewSize = b.dataset.size; $$('[data-size]').forEach(x => x.classList.toggle('selected', x === b)); renderPreview(); })); $$('[data-state]').forEach(b => b.addEventListener('click', () => { previewState = b.dataset.state; $$('[data-state]').forEach(x => x.classList.toggle('selected', x === b)); renderPreview(); }));
function applyImportedArt(skin) { const background = store.assets.find(asset => asset.id === skin.backgroundAsset); const root = $('#previewScreen'); root.style.backgroundImage = background ? `linear-gradient(rgb(0 0 0 / .32), rgb(0 0 0 / .32)), url("${background.data}")` : ''; root.style.backgroundSize = background ? `${skin.backgroundScale}% auto` : ''; root.style.backgroundPosition = background ? `${skin.backgroundPositionX}% ${skin.backgroundPositionY}%` : ''; const keys = Object.keys(icons); $$('.preview-nav button').forEach((button, index) => { const key = keys[index], asset = store.assets.find(item => item.id === skin.symbolAssets[key]), scale = (Number(skin.symbolScale?.[key]) || 100) / 100; button.classList.toggle('active', index === previewModeIndex); button.innerHTML = asset ? `<img class="preview-symbol-image" src="${asset.data}" alt="" style="transform:scale(${scale})"><small>${escape(labels[key])}</small>` : `<span class="preview-symbol-glyph" style="font-size:${1.05 * scale}rem">${escape(skin.symbols[key])}</span><small>${escape(labels[key])}</small>`; }); }
const importedArtStyle = document.createElement('style'); importedArtStyle.textContent = '.preview-symbol-image{width:22px;height:22px;object-fit:contain}.preview-seats div{border-color:color-mix(in srgb,#5b594f calc(var(--seat-border,70) * 1%),transparent);background:color-mix(in srgb,var(--surface) calc(var(--seat-opacity,100) * 1%),transparent);backdrop-filter:blur(calc(var(--seat-blur,0) * 1px))}.preview-screen[data-seat="glass"] .preview-seats div{background:color-mix(in srgb,var(--surface) calc(var(--seat-opacity,100) * .72%),transparent)}'; document.head.append(importedArtStyle);
$('#backgroundAsset').addEventListener('input', () => { draft.backgroundAsset = $('#backgroundAsset').value; changed(); });
$('#assetFile').addEventListener('change', () => { $('#assetStatus').textContent = ''; });
function readData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function scaleForStudio(file, placement) { const source = await readData(file); const image = new Image(); image.src = source; await image.decode(); const limit = placement === 'symbol' ? 256 : 1280, ratio = Math.min(1, limit / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.naturalWidth * ratio)); canvas.height = Math.max(1, Math.round(image.naturalHeight * ratio)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); for (let quality = .88; quality >= .4; quality -= .08) { const data = canvas.toDataURL('image/webp', quality); if (data.length * .75 <= 700000) return { data, resized: canvas.width !== image.naturalWidth || canvas.height !== image.naturalHeight }; } throw new Error('This image could not be reduced below the local-library limit.'); }
window.addEventListener('message', event => { if (event.origin !== location.origin || event.data?.type !== 'fivefold-arc:appearance-studio-key') return; developerKey = String(event.data.key || ''); void loadCatalog(); });
async function loadCatalog() { try { const response = await fetch('/api/appearance-studio/catalog', { headers: { 'x-feedback-portal-key': developerKey } }); if (response.ok) { const remote = (await response.json()).catalog; if (remote?.skins?.length) { remote.assets = await Promise.all((remote.assets || []).map(loadAssetData)); store = remote; if (!store.skins.some(skin => skin.id === 'neutral')) store.skins.unshift(neutral); selectedId = store.selected || 'neutral'; selectSkin(selectedId); } } } catch { /* direct file use keeps the optional browser cache */ } }
store.skins.forEach(normalizeSkin);
selectSkin(selectedId);
if (developerKey) void loadCatalog();
$('#restoreCatalogButton').addEventListener('click', async () => { const file = $('#catalogBackupFile').files[0], status = $('#catalogRestoreStatus'); if (!file) { status.textContent = 'Choose the saved appearance-studio-catalog.json backup first.'; return; } if (file.size > 8 * 1024 * 1024) { status.textContent = 'This catalog is larger than the 8 MB protected catalog limit.'; return; } if (!confirm('Restore this backup? It replaces the current protected Studio catalog.')) return; try { const restored = JSON.parse(await file.text()); if (!Array.isArray(restored.skins) || !Array.isArray(restored.assets)) throw new Error('That file is not an Appearance Studio catalog.'); const previousStore = clone(store), previousSelected = selectedId; store = { skins: restored.skins, assets: restored.assets, selected: restored.selected || 'neutral' }; if (!store.skins.some(skin => skin.id === 'neutral')) store.skins.unshift(clone(neutral)); selectedId = store.selected; if (!await saveCatalog()) { store = previousStore; selectedId = previousSelected; return; } selectSkin(selectedId); status.textContent = `Restored ${store.skins.length - 1} saved skin${store.skins.length === 2 ? '' : 's'} and ${store.assets.length} image${store.assets.length === 1 ? '' : 's'}.`; toast('Protected Studio catalog restored.'); } catch (error) { status.textContent = error.message || 'This catalog backup could not be restored.'; } });
$('#importAssetButton').addEventListener('click', async () => { const file = $('#assetFile').files[0], name = $('#assetName').value.trim(), source = $('#assetSource').value.trim(), placement = $('#assetPlacement').value, status = $('#assetStatus'); if (!file || !name || !source) { status.textContent = 'Choose an image and provide both its name and rights/source note.'; return; } if (!['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'].includes(file.type) || file.size > 1500000) { status.textContent = 'Use a PNG, JPEG, WebP, or SVG up to 1.5 MB.'; return; } try { status.textContent = 'Scaling image for the server catalog…'; const result = file.size > 700000 || file.type === 'image/svg+xml' ? await scaleForStudio(file, placement) : { data: await readData(file), resized: false }; store.assets.unshift({ id: `asset-${Date.now()}`, name, source, placement, data: result.data }); if (!await saveCatalog()) { store.assets.shift(); return; } $('#assetFile').value = ''; $('#assetName').value = ''; $('#assetSource').value = ''; status.textContent = `${name} imported to the server catalog${result.resized ? ' and scaled to fit' : ''}.`; renderEditor(); renderPreview(); } catch (error) { status.textContent = error.message || 'This image could not be prepared for the server catalog.'; } });
const studioScaleStyle = document.createElement('style'); studioScaleStyle.textContent = '.symbol-controls .symbol-control{display:grid!important;grid-template-columns:minmax(0,1fr) 76px 112px;gap:8px;align-items:center}.symbol-controls .symbol-control>span{grid-column:1/2}.symbol-controls .symbol-control input[type=range]{grid-column:1/-1;width:100%;margin:3px 0 0}.symbol-controls .symbol-control>small:last-child{grid-column:1/-1;color:#d8b36b}.preview-symbol-image{transition:transform .12s ease}'; document.head.append(studioScaleStyle);
const atmosphereStyle = document.createElement('style'); atmosphereStyle.textContent = '.atmosphere-controls{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.atmosphere-controls label{margin-top:0!important;font-size:.68rem!important}.atmosphere-controls input[type=color]{height:38px;min-height:38px;margin-top:4px;padding:3px}.atmosphere-controls select{margin-top:4px}.atmosphere-controls .atmosphere-strength{grid-column:1/-1}.atmosphere-strength output{float:right;color:#d8b36b}.atmosphere-strength input{width:100%;min-height:auto;margin:7px 0 0;padding:0}.preview-screen:before,.preview-screen:after{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none}.preview-screen:before{background:radial-gradient(circle at var(--atmosphere-position),color-mix(in srgb,var(--atmosphere) calc(var(--atmosphere-strength) * 100%),transparent),transparent 58%)}.preview-screen[data-atmosphere=light]:after{background:#fff;opacity:.08}.preview-screen[data-atmosphere=custom]:after{background:linear-gradient(180deg,color-mix(in srgb,var(--atmosphere) calc(var(--atmosphere-strength) * 55%),transparent),transparent 48%)}.preview-screen[data-art=rays]:after,.preview-screen[data-art=grain]:after,.preview-screen[data-art=mist]:after,.preview-screen[data-art=stars]:after{opacity:.18}.preview-screen[data-art=rays]:after{background:repeating-conic-gradient(from 0deg at 50% 35%,transparent 0 12deg,var(--accent) 13deg 14deg,transparent 15deg 28deg)}.preview-screen[data-art=grain]:after{background:repeating-linear-gradient(70deg,transparent 0 3px,#fff 4px 5px)}.preview-screen[data-art=mist]:after{background:radial-gradient(ellipse at 10% 18%,#fff8,transparent 32%),radial-gradient(ellipse at 88% 66%,var(--atmosphere),transparent 42%);filter:blur(18px)}.preview-screen[data-art=stars]:after{background-image:radial-gradient(circle,#fff 0 1px,transparent 1.5px),radial-gradient(circle,var(--accent) 0 1px,transparent 1.5px);background-position:0 0,17px 23px;background-size:31px 37px,43px 47px}'; document.head.append(atmosphereStyle);
function applyAtmosphere(skin) { const root = $('#previewScreen'); root.style.setProperty('--atmosphere', skin.atmosphereColor); root.style.setProperty('--atmosphere-strength', `${skin.atmosphereStrength / 100}`); root.style.setProperty('--atmosphere-position', skin.atmospherePosition === 'bottom' ? '50% 100%' : skin.atmospherePosition === 'center' ? '50% 50%' : '50% 0%'); }
const atmosphereLayerStyle = document.createElement('style'); atmosphereLayerStyle.textContent = '.preview-screen[data-art]:before{background:radial-gradient(circle at var(--atmosphere-position),color-mix(in srgb,var(--atmosphere) calc(var(--atmosphere-strength) * 100%),transparent),transparent 58%)}'; document.head.append(atmosphereLayerStyle);
const exactPreviewStyle = document.createElement('style'); exactPreviewStyle.textContent = '.preview-stage>.phone-preview{display:none}.exact-preview{box-sizing:content-box;display:block;overflow:hidden;border:8px solid #090a0a;border-radius:34px;background:#090a0a;box-shadow:0 20px 70px #0008;pointer-events:none}.exact-preview.size-phone{width:393px;height:852px}.exact-preview.size-compact{width:320px;height:700px}.exact-preview.size-desktop{width:min(740px,100%);height:760px;border-radius:18px}@media(max-width:720px){.exact-preview.size-phone{width:min(393px,100%);height:min(852px,calc(100vh - 170px))}.exact-preview.size-compact{height:700px}.exact-preview.size-desktop{height:600px}}'; document.head.append(exactPreviewStyle);
const preflightSizes = [{ id: 'phone', label: '393 × 852' }, { id: 'compact', label: '320 × 700' }];
const preflightPlayers = [4, 6, 8];
const nextFrame = () => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
const preflightPanel = document.createElement('section'); preflightPanel.className = 'preflight-panel'; preflightPanel.innerHTML = '<p class="kicker">LOCAL PREFLIGHT</p><h2>Draft readiness</h2><p class="helper">Checks the exact app preview at both supported phone sizes, 4/6/8-player tables, and every counter mode. It never saves or publishes your draft.</p><button id="runPreflightButton" class="secondary-action" type="button">Run preflight</button><p id="preflightSummary" class="preflight-summary" aria-live="polite">Not run for this draft.</p><ul id="preflightList" class="preflight-list" hidden></ul>'; $('.validation-panel').insertBefore(preflightPanel, $('.validation-panel').children[1]);
function preflightLabel({ size, players, mode }) { return `${size.label} · ${players} players · ${labels[mode]}`; }
function renderPreflight(results, extraChecks) { const checks = [...extraChecks, ...results], failed = checks.filter(check => !check.pass), screens = results.filter(check => check.pass), summary = $('#preflightSummary'), list = $('#preflightList'); summary.textContent = failed.length ? `${failed.length} of ${checks.length} local checks need attention. Review the listed exact-app screens before saving this draft.` : `${screens.length} exact-app screens and ${extraChecks.length} draft checks passed locally. Real-device touch and table-distance review still need a playtest.`; summary.className = `preflight-summary ${failed.length ? 'fail' : 'pass'}`; list.hidden = false; list.innerHTML = checks.map(check => `<li class="${check.pass ? 'pass' : 'fail'}"><span>${check.pass ? '✓' : '!'}</span><div><strong>${check.label}</strong><small>${check.detail}</small></div></li>`).join(''); }
async function runPreflight() { const button = $('#runPreflightButton'), frame = $('#exactPreview'); if (button.disabled) return; button.disabled = true; button.textContent = 'Running…'; $('#preflightSummary').textContent = 'Checking the exact app preview…'; $('#preflightSummary').className = 'preflight-summary review'; $('#preflightList').hidden = true; const remembered = { previewSize, previewPlayers, previewMode, previewModeIndex, previewState, showingBaseline }, skin = clone(draft), extraChecks = Object.entries(icons).map(([mode]) => { const scale = Number(skin.symbolScale?.[mode] || 100); return { label: `${labels[mode]} icon scale is within 60–200%`, pass: scale >= 60 && scale <= 200, detail: `${scale}% selected for this draft` }; }), results = []; try { for (const size of preflightSizes) for (const players of preflightPlayers) for (const mode of Object.keys(icons)) { previewSize = size.id; previewPlayers = players; previewMode = mode; previewModeIndex = Object.keys(icons).indexOf(mode); previewState = 'turn'; showingBaseline = false; renderPreview(); await nextFrame(); const root = frame.contentDocument?.documentElement, hasViewport = Boolean(root?.clientWidth && root?.clientHeight), fits = hasViewport && root.scrollWidth <= root.clientWidth && root.scrollHeight <= root.clientHeight; results.push({ label: preflightLabel({ size, players, mode }), pass: fits, detail: fits ? 'Exact app rendered without document overflow' : 'Exact app did not fit this preview; inspect this configuration' }); } } catch { results.push({ label: 'Exact app preview connection', pass: false, detail: 'The local exact preview could not be checked. Reload Studio and try again.' }); } finally { previewSize = remembered.previewSize; previewPlayers = remembered.previewPlayers; previewMode = remembered.previewMode; previewModeIndex = remembered.previewModeIndex; previewState = remembered.previewState; showingBaseline = remembered.showingBaseline; renderPreview(); button.disabled = false; button.textContent = 'Run preflight'; renderPreflight(results, extraChecks); } }
function renderExactPreview() { const skin = showingBaseline ? neutral : draft, frame = $('#exactPreview'); frame.className = `exact-preview size-${previewSize}`; frame.contentWindow?.postMessage({ type: 'fivefold-arc:appearance-skin', skin: { ...skin, previewState, previewMode, previewPlayers, backgroundData: store.assets.find(asset => asset.id === skin.backgroundAsset)?.data || '', sealData: store.assets.find(asset => asset.id === skin.sealAsset)?.data || '', symbolData: Object.fromEntries(Object.keys(icons).map(key => [key, store.assets.find(asset => asset.id === skin.symbolAssets?.[key])?.data || ''])) } }, location.origin); }
const podPreviewControl = document.createElement('div'); podPreviewControl.className = 'segmented'; podPreviewControl.setAttribute('role', 'group'); podPreviewControl.setAttribute('aria-label', 'Preview pod size'); podPreviewControl.innerHTML = '<button data-preview-players="4" class="selected" type="button">4 players</button><button data-preview-players="6" type="button">6 players</button><button data-preview-players="8" type="button">8 players</button>'; $('.preview-toolbar').append(podPreviewControl); $$('[data-preview-players]').forEach(button => button.addEventListener('click', () => { previewPlayers = Number(button.dataset.previewPlayers); $$('[data-preview-players]').forEach(item => item.classList.toggle('selected', item === button)); renderPreview(); }));
const modePreviewControl = document.createElement('div'); modePreviewControl.className = 'segmented'; modePreviewControl.setAttribute('role', 'group'); modePreviewControl.setAttribute('aria-label', 'Preview counter mode'); modePreviewControl.innerHTML = Object.entries(labels).map(([mode, label]) => `<button data-preview-mode="${mode}" class="${mode === previewMode ? 'selected' : ''}" type="button">${label}</button>`).join(''); $('.preview-toolbar').append(modePreviewControl); $$('[data-preview-mode]').forEach(button => button.addEventListener('click', () => { previewMode = button.dataset.previewMode; previewModeIndex = Object.keys(icons).indexOf(previewMode); $$('[data-preview-mode]').forEach(item => item.classList.toggle('selected', item === button)); renderPreview(); }));
$('#exactPreview').addEventListener('load', renderExactPreview); $('#runPreflightButton').addEventListener('click', runPreflight); renderPreview();
const exactPreviewPlacementStyle = document.createElement('style'); exactPreviewPlacementStyle.textContent = '.preview-area{display:flex;flex-direction:column;align-items:center}.preview-toolbar,.compare-note{width:100%;flex:none}.preview-stage{display:contents}.exact-preview{flex:none;margin:16px 0}'; document.head.append(exactPreviewPlacementStyle);
const backgroundArtControlsStyle = document.createElement('style'); backgroundArtControlsStyle.textContent = '.background-art-controls{display:grid;gap:8px;margin-top:10px}.background-art-controls label{display:grid!important;grid-template-columns:1fr auto;gap:5px;margin:0!important;font-size:.68rem!important}.background-art-controls output{color:#d8b36b}.background-art-controls input{grid-column:1/-1;width:100%;min-height:auto;margin:0;padding:0}'; document.head.append(backgroundArtControlsStyle);
const buttonControlsStyle = document.createElement('style'); buttonControlsStyle.textContent = '.preview-end-turn{border-color:color-mix(in srgb,var(--accent) calc(var(--button-border,70) * 1%),transparent);background:color-mix(in srgb,var(--accent) calc(var(--button-opacity,100) * 1%),transparent);backdrop-filter:blur(calc(var(--button-blur,0) * 1px))}.preview-adjust button{border-color:color-mix(in srgb,#58574f calc(var(--life-button-border,70) * 1%),transparent);background:color-mix(in srgb,var(--surface) calc(var(--life-button-opacity,100) * 1%),transparent);backdrop-filter:blur(calc(var(--life-button-blur,0) * 1px))}'; document.head.append(buttonControlsStyle);
function applyButtonControls(skin) { const root = $('#previewScreen'); ['button','lifeButton','customLife','commanderTax'].forEach(prefix => { const css = prefix.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`); root.style.setProperty(`--${css}-opacity`, skin[`${prefix}Opacity`]); root.style.setProperty(`--${css}-blur`, skin[`${prefix}Blur`]); root.style.setProperty(`--${css}-border`, skin[`${prefix}Border`]); }); }
['buttonOpacity','buttonBlur','buttonBorder','lifeButtonOpacity','lifeButtonBlur','lifeButtonBorder','customLifeOpacity','customLifeBlur','customLifeBorder','commanderTaxOpacity','commanderTaxBlur','commanderTaxBorder'].forEach(key => $(`#${key}`).addEventListener('input', event => { draft[key] = Number(event.target.value); $(`#${key}Value`).textContent = `${event.target.value}${key.endsWith('Blur') ? 'px' : '%'}`; changed(); }));
$('#backgroundAutoFit').addEventListener('click', () => { draft.backgroundScale = 100; draft.backgroundPositionX = 50; draft.backgroundPositionY = 50; renderEditor(); changed(); });
renderPreview();
