const $ = (selector, root = document) => root.querySelector(selector); const api = "/api";
let connectionId = null; let room = null; let seatId = Number(localStorage.getItem("fivefold-duel:seat")); let stream = null; let live = false;
const views = ["home", "create", "join", "duel"].map(id => $(`#${id}`));
function show(id) { views.forEach(view => view.hidden = view.id !== id); }
function ownSeat() { return Number.isInteger(seatId) ? seatId : null; }
async function request(path, options = {}) { if (room && options.method && options.method !== "GET" && !live) throw new Error("You are offline. Changes are paused until this phone reconnects; nothing is queued."); const response = await fetch(`${api}${path}`, { ...options, headers: { "content-type": "application/json", ...(connectionId ? { "x-connection-id": connectionId } : {}), ...(options.headers || {}) } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || "Something went wrong."); return payload; }
async function ensureConnection() { if (connectionId) return; const result = await request("/connections", { method: "POST", body: "{}" }); connectionId = result.connectionId; localStorage.setItem("fivefold-duel:connection", connectionId); }
function saveSeat(code, nextSeat, token) { seatId = nextSeat; localStorage.setItem("fivefold-duel:room", code); localStorage.setItem("fivefold-duel:seat", String(nextSeat)); localStorage.setItem(`fivefold-duel:${code}:token`, token); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character])); }
function phaseHint() { if (!room) return ""; if (room.duel.turnNumber === 1 && room.duel.activeSeatId === room.duelists[0].seatId) return room.duel.phaseIndex === 0 ? "First turn: the first Duelist does not draw." : room.duel.phaseIndex === 3 ? "First turn: no Battle Phase." : "First-turn reminder"; return "Optional phase guide — card effects remain player-managed."; }
function renderLog() { const log = [...room.duel.lifePointLog].reverse(); $("#lpLog").innerHTML = log.length ? log.map(entry => { const duelist = room.duelists[entry.seatId]; const sign = entry.delta > 0 ? "+" : ""; const correct = entry.seatId === ownSeat() ? `<button class="correct-entry" data-correct="${entry.id}">Correct</button>` : ""; return `<li class="${entry.kind === "correction" ? "correction" : ""}"><span><strong>${escapeHtml(duelist.name)}</strong> <span class="${entry.delta > 0 ? "gain" : "loss"}">${sign}${entry.delta} LP</span><span class="entry-detail">${entry.kind === "correction" ? "Correction · " : ""}${escapeHtml(entry.note || "No note")}</span></span><span class="entry-total">${entry.after.toLocaleString()}${correct}</span></li>`; }).join("") : "<li><span>No LP changes yet.</span><span>8,000</span></li>"; $("#lpLog").querySelectorAll("[data-correct]").forEach(button => button.addEventListener("click", () => correctEntry(button.dataset.correct))); }
function render() { if (!room) return; show("duel"); $("#code").textContent = `DUEL ${room.code}`; $("#format").textContent = room.matchFormat === "best_of_three" ? "BEST OF 3" : "SINGLE DUEL"; $("#duelNumber").textContent = room.duelNumber; $("#score").textContent = `${room.duelists[0].name} ${room.matchScore[0]} — ${room.matchScore[1]} ${room.duelists[1].name}`;
  const active = room.duelists[room.duel.activeSeatId]; const currentPhase = ["Draw", "Standby", "Main 1", "Battle", "Main 2", "End"][room.duel.phaseIndex]; document.body.dataset.phase = currentPhase.toLowerCase().replace(/\s/g, "-"); $("#turnLabel").textContent = `${active.name.toUpperCase()}'S TURN · TURN ${room.duel.turnNumber}`; $("#phase").textContent = currentPhase; $("#turnHint").textContent = phaseHint(); const mine = ownSeat(); $("#advancePhase").disabled = mine !== room.duel.activeSeatId || Boolean(room.duel.outcome); $("#undoPhase").disabled = !room.duel.phaseHistory.length || Boolean(room.duel.outcome);
  const cards = $("#lifeCards"); cards.innerHTML = ""; const template = $("#lifeCard"); room.duelists.forEach((duelist, index) => { const card = template.content.firstElementChild.cloneNode(true); card.classList.toggle("mine", index === mine); $(".seat-name", card).textContent = duelist.name; $(".life-total", card).textContent = room.duel.lifePoints[index].toLocaleString(); $(".ownership", card).textContent = index === mine ? "YOUR LIFE POINTS" : "CONFIRMED OPPONENT LP"; card.querySelectorAll("[data-delta]").forEach(button => button.addEventListener("click", () => adjust(Number(button.dataset.delta)))); card.querySelector(".custom-lp").addEventListener("submit", event => { event.preventDefault(); const form = new FormData(event.currentTarget); adjust(Number(form.get("delta")), String(form.get("note"))); }); card.querySelectorAll("button,input").forEach(control => control.disabled = index !== mine || Boolean(room.duel.outcome)); cards.append(card); }); renderLog();
  const tools = { randomHistory: [], notes: [], counters: [], tokens: [], ...(room.tools || {}) }; $("#randomHistory").textContent = tools.randomHistory.length ? tools.randomHistory.map(item => `${room.duelists[item.seatId].name}: ${item.sides === 2 ? (item.value === 1 ? "Heads" : "Tails") : `d${item.sides} = ${item.value}`}`).join(" · ") : "No shared random result yet."; $("#sharedNotes").innerHTML = tools.notes.map(item => `<li><span><strong>${escapeHtml(room.duelists[item.seatId].name)}</strong><span class="entry-detail">${escapeHtml(item.text)}</span></span></li>`).join("") || "<li><span>No shared notes.</span></li>"; $("#sharedCounters").innerHTML = tools.counters.map(item => `<li><span><strong>${escapeHtml(item.label)}</strong><span class="entry-detail">${item.value}</span></span>${item.seatId === mine ? `<button class="correct-entry" data-remove-counter="${item.id}">Remove</button>` : ""}</li>`).join("") || "<li><span>No shared counters.</span></li>"; $("#sharedTokens").innerHTML = tools.tokens.map(item => `<li><span><strong>${escapeHtml(item.name)}</strong><span class="entry-detail">ATK ${item.atk} / DEF ${item.def}${item.level ? ` · Level ${item.level}` : ""}</span></span>${item.seatId === mine ? `<button class="correct-entry" data-remove-token="${item.id}">Remove</button>` : ""}</li>`).join("") || "<li><span>No Token notes.</span></li>"; document.querySelectorAll("[data-remove-counter]").forEach(button => button.addEventListener("click", () => removeToolItem("counter", button.dataset.removeCounter))); document.querySelectorAll("[data-remove-token]").forEach(button => button.addEventListener("click", () => removeToolItem("token", button.dataset.removeToken)));
  const outcome = $("#outcomePanel"); $("#outcomeButtons").innerHTML = room.duel.outcome ? "" : room.duelists.map(item => `<button class="secondary" data-winner="${item.seatId}">${escapeHtml(item.name)} won</button>`).join(""); $("#outcomeButtons").querySelectorAll("[data-winner]").forEach(button => button.addEventListener("click", () => outcomeAction(Number(button.dataset.winner)))); const next = $("#nextDuelChoice"); const complete = room.matchFormat === "single_duel" || Math.max(...room.matchScore) >= 2; next.hidden = !room.duel.outcome || complete; if (room.duel.outcome && !complete) { const loser = room.duel.outcome.winnerSeatId === 0 ? 1 : 0; $("#nextDuelPrompt").textContent = `${room.duelists[loser].name} lost the prior Duel and chooses who goes first.`; } outcome.querySelector("h2").textContent = room.duel.outcome ? (complete ? "Match complete" : "Start next Duel") : "Finish this Duel";
}
async function adjust(delta, note = "") { try { await request(`/duels/${room.code}/adjust`, { method: "POST", body: JSON.stringify({ delta, note }) }); } catch (error) { alert(error.message); } }
async function correctEntry(entryId) { const entered = prompt("Correction amount. Use + or - LP, for example 200 or -500."); if (entered === null) return; const delta = Number(entered); if (!Number.isInteger(delta) || !delta) return alert("Enter a non-zero whole number."); const note = prompt("What is being corrected? (optional)") || ""; try { await request(`/duels/${room.code}/correct`, { method: "POST", body: JSON.stringify({ entryId, delta, note }) }); } catch (error) { alert(error.message); } }
async function outcomeAction(winnerSeatId) { try { await request(`/duels/${room.code}/outcome`, { method: "POST", body: JSON.stringify({ winnerSeatId }) }); } catch (error) { alert(error.message); } }
function setLive(nextLive) { live = nextLive; $("#offlineBanner").hidden = nextLive; $("#connection").textContent = nextLive ? (room?.recovered ? "Recovered Duel · confirmed live" : "Confirmed live table") : "Offline — reconnecting"; }
function connectEvents() { stream?.close(); setLive(false); stream = new EventSource(`/api/duels/${room.code}/events`); stream.addEventListener("snapshot", event => { room = JSON.parse(event.data); render(); }); stream.onerror = () => setLive(false); stream.onopen = () => setLive(true); }
$("#showCreate").addEventListener("click", () => show("create")); $("#showJoin").addEventListener("click", () => show("join")); document.querySelectorAll("[data-home]").forEach(button => button.addEventListener("click", () => show("home")));
$("#createForm").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await ensureConnection(); const result = await request("/duels", { method: "POST", body: JSON.stringify({ name: form.get("name"), matchFormat: form.get("matchFormat") }) }); room = result.snapshot; saveSeat(room.code, result.seatId, result.reclaimToken); connectEvents(); } catch (error) { alert(error.message); } });
$("#joinForm").addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const code = String(form.get("code")).toUpperCase().replace(/[^A-Z0-9]/g, ""); try { await ensureConnection(); const snapshot = (await request(`/duels/${code}`)).snapshot; const open = snapshot.duelists.find(item => !item.claimed); if (!open) throw new Error("Both Duelist seats are already claimed."); const result = await request(`/duels/${code}/claim`, { method: "POST", body: JSON.stringify({ seatId: open.seatId, name: form.get("name") }) }); room = result.snapshot; saveSeat(room.code, result.seatId, result.reclaimToken); $("#joinError").textContent = ""; connectEvents(); } catch (error) { $("#joinError").textContent = error.message; } });
$("#advancePhase").addEventListener("click", async () => { try { await request(`/duels/${room.code}/phase/advance`, { method: "POST", body: "{}" }); } catch (error) { alert(error.message); } }); $("#undoPhase").addEventListener("click", async () => { try { await request(`/duels/${room.code}/phase/undo`, { method: "POST", body: "{}" }); } catch (error) { alert(error.message); } });
$("#nextDuelChoice").addEventListener("click", async event => { const firstSeatId = event.target.dataset.firstSeat; if (firstSeatId === undefined) return; try { await request(`/duels/${room.code}/next-duel`, { method: "POST", body: JSON.stringify({ firstSeatId: Number(firstSeatId) }) }); } catch (error) { alert(error.message); } }); $("#copyCode").addEventListener("click", () => navigator.clipboard?.writeText(room.code));
document.querySelectorAll("[data-random]").forEach(button => button.addEventListener("click", async () => { try { await request(`/duels/${room.code}/randomize`, { method: "POST", body: JSON.stringify({ sides: Number(button.dataset.random) }) }); } catch (error) { alert(error.message); } })); $("#sharedNoteForm").addEventListener("submit", async event => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { await request(`/duels/${room.code}/shared-notes`, { method: "POST", body: JSON.stringify({ text: form.get("note") }) }); element.reset(); } catch (error) { alert(error.message); } });
$("#counterForm").addEventListener("submit", async event => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { await request(`/duels/${room.code}/counters`, { method: "POST", body: JSON.stringify({ label: form.get("label"), value: Number(form.get("value")) }) }); element.reset(); element.elements.value.value = "0"; } catch (error) { alert(error.message); } }); $("#tokenForm").addEventListener("submit", async event => { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { await request(`/duels/${room.code}/tokens`, { method: "POST", body: JSON.stringify({ name: form.get("name"), atk: Number(form.get("atk")), def: Number(form.get("def")), level: Number(form.get("level")) }) }); element.reset(); } catch (error) { alert(error.message); } }); async function removeToolItem(type, itemId) { try { await request(`/duels/${room.code}/tools/remove`, { method: "POST", body: JSON.stringify({ type, itemId }) }); } catch (error) { alert(error.message); } }
async function restoreSavedSeat() { const code = localStorage.getItem("fivefold-duel:room"); const savedSeatId = Number(localStorage.getItem("fivefold-duel:seat")); const token = code && localStorage.getItem(`fivefold-duel:${code}:token`); if (!code || !Number.isInteger(savedSeatId) || !token) return; try { await ensureConnection(); const result = await request(`/duels/${code}/claim`, { method: "POST", body: JSON.stringify({ seatId: savedSeatId, reclaimToken: token }) }); room = result.snapshot; saveSeat(code, result.seatId, result.reclaimToken); connectEvents(); } catch (error) { localStorage.removeItem("fivefold-duel:room"); localStorage.removeItem("fivefold-duel:seat"); localStorage.removeItem(`fivefold-duel:${code}:token`); $("#connection").textContent = "Saved Duel is no longer available"; } }
void restoreSavedSeat();
