import test from "node:test";
import assert from "node:assert/strict";
import { DuelRoomService, PHASES } from "./room-service.js";
import { MemoryDuelStore } from "./duel-store.js";

test("two Duelists retain player-owned LP and a correction record", () => { const service = new DuelRoomService({ now: () => 100 }); const a = service.connect(); const created = service.create(a.connectionId, { name: "A" }); const b = service.connect(); service.claim(created.snapshot.code, b.connectionId, { seatId: 1, name: "B" }); service.adjust(created.snapshot.code, a.connectionId, { delta: -1200, note: "battle" }); const room = service.room(created.snapshot.code); const entry = room.duel.lifePointLog[0]; service.correct(created.snapshot.code, a.connectionId, { entryId: entry.id, delta: 200, note: "corrected" }); assert.equal(room.duel.lifePoints[0], 7000); assert.deepEqual(room.duel.lifePointLog.map(item => item.kind), ["adjustment", "correction"]); assert.equal(room.duel.lifePointLog[1].correctsEntryId, entry.id); assert.throws(() => service.correct(created.snapshot.code, b.connectionId, { entryId: entry.id, delta: -1 }), /own LP entries/); });
test("phase tracking rotates after End and preserves Match score between Duels", () => { const service = new DuelRoomService(); const a = service.connect(); const created = service.create(a.connectionId, {}); const b = service.connect(); service.claim(created.snapshot.code, b.connectionId, { seatId: 1 }); for (let index = 0; index < PHASES.length; index++) service.advancePhase(created.snapshot.code, a.connectionId); const room = service.room(created.snapshot.code); assert.equal(room.duel.activeSeatId, 1); assert.equal(room.duel.turnNumber, 2); service.declareOutcome(created.snapshot.code, a.connectionId, { winnerSeatId: 0 }); service.nextDuel(created.snapshot.code, b.connectionId, { firstSeatId: 1 }); assert.deepEqual(room.matchScore, [1, 0]); assert.deepEqual(room.duel.lifePoints, [8000, 8000]); assert.equal(room.duel.activeSeatId, 1); });
test("a saved reclaim token moves a seat to a fresh connection and rejects the old owner", () => { const service = new DuelRoomService(); const first = service.connect(); const created = service.create(first.connectionId, { name: "A" }); const replacement = service.connect(); const reclaimed = service.claim(created.snapshot.code, replacement.connectionId, { seatId: 0, reclaimToken: created.reclaimToken }); assert.equal(reclaimed.seatId, 0); assert.throws(() => service.adjust(created.snapshot.code, first.connectionId, { delta: -1 }), /Claim a Duelist seat first/); service.adjust(created.snapshot.code, replacement.connectionId, { delta: -1 }); assert.equal(service.room(created.snapshot.code).duel.lifePoints[0], 7999); });
test("restart recovery preserves the Duel but requires each original token", () => { const store = new MemoryDuelStore(); const first = new DuelRoomService({ store }); const a = first.connect(); const created = first.create(a.connectionId, { name: "A" }); first.adjust(created.snapshot.code, a.connectionId, { delta: -500 }); const restarted = new DuelRoomService({ store }); const intruder = restarted.connect(); assert.throws(() => restarted.claim(created.snapshot.code, intruder.connectionId, { seatId: 0 }), /original phone/); const returning = restarted.connect(); const claimed = restarted.claim(created.snapshot.code, returning.connectionId, { seatId: 0, reclaimToken: created.reclaimToken }); assert.equal(claimed.snapshot.duel.lifePoints[0], 7500); assert.equal(claimed.snapshot.recovered, true); });
test("shared random results and notes are confirmed table utilities", () => { const service = new DuelRoomService(); const a = service.connect(); const created = service.create(a.connectionId, {}); service.randomize(created.snapshot.code, a.connectionId, { sides: 6 }); service.addSharedNote(created.snapshot.code, a.connectionId, { text: "LP paid for effect" }); const tools = service.snapshot(service.room(created.snapshot.code)).tools; assert.equal(tools.randomHistory[0].sides, 6); assert.ok(tools.randomHistory[0].value >= 1 && tools.randomHistory[0].value <= 6); assert.equal(tools.notes[0].text, "LP paid for effect"); });
test("Duelists can add and remove only their own shared counters and Token notes", () => { const service = new DuelRoomService(); const a = service.connect(); const created = service.create(a.connectionId, {}); const b = service.connect(); service.claim(created.snapshot.code, b.connectionId, { seatId: 1 }); service.addCounter(created.snapshot.code, a.connectionId, { label: "Spell Counter", value: 3 }); service.addToken(created.snapshot.code, a.connectionId, { name: "Sheep Token", atk: 0, def: 0, level: 1 }); const tools = service.snapshot(service.room(created.snapshot.code)).tools; assert.equal(tools.counters[0].label, "Spell Counter"); assert.equal(tools.tokens[0].name, "Sheep Token"); assert.throws(() => service.removeToolItem(created.snapshot.code, b.connectionId, { type: "counter", itemId: tools.counters[0].id }), /only your own/); service.removeToolItem(created.snapshot.code, a.connectionId, { type: "counter", itemId: tools.counters[0].id }); assert.equal(service.snapshot(service.room(created.snapshot.code)).tools.counters.length, 0); });
