import { createHash, randomBytes } from "node:crypto";

const CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const PHASES = ["Draw", "Standby", "Main 1", "Battle", "Main 2", "End"];

function id() { return randomBytes(18).toString("base64url"); }
function tokenHash(token) { return createHash("sha256").update(token).digest("base64url"); }
function roomCode() { return Array.from({ length: 6 }, () => CODE_ALPHABET[randomBytes(1)[0] % CODE_ALPHABET.length]).join(""); }
function name(value, fallback) { const cleaned = String(value ?? "").trim().replace(/\s+/g, " "); return cleaned ? cleaned.slice(0, 24) : fallback; }
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function emptyTools() { return { randomHistory: [], notes: [], counters: [], tokens: [] }; }

export class DuelRoomService {
  constructor({ now = () => Date.now(), store = null } = {}) { this.now = now; this.store = store; this.rooms = new Map((store?.load() || []).map(room => [room.code, { ...room, recovered: true, duelists: room.duelists.map(duelist => ({ ...duelist, connectionId: null })) }])); this.connections = new Map(); this.listeners = new Map(); }
  persist() { if (!this.store) return; this.store.save([...this.rooms.values()].map(room => ({ ...room, duelists: room.duelists.map(({ connectionId, ...duelist }) => duelist) }))); }
  connect() { const connectionId = id(); this.connections.set(connectionId, { seatKey: null }); return { connectionId }; }
  room(code) { const room = this.rooms.get(String(code).toUpperCase()); if (!room) throw Object.assign(new Error("Duel not found."), { status: 404, code: "NOT_FOUND" }); return room; }
  owner(room, connectionId) { const connection = this.connections.get(connectionId); if (!connection?.seatKey) throw Object.assign(new Error("Claim a Duelist seat first."), { status: 403, code: "NOT_SEATED" }); const [, seatId] = connection.seatKey.split(":"); if (room.code !== connection.seatKey.slice(0, 6)) throw Object.assign(new Error("This connection does not belong to this Duel."), { status: 403, code: "NOT_SEATED" }); return Number(seatId); }
  snapshot(room) { return clone({ code: room.code, version: room.version, createdAt: room.createdAt, profile: "tcg_tabletop", matchFormat: room.matchFormat, duelists: room.duelists.map(({ connectionId, reclaimTokenHash, ...duelist }) => ({ ...duelist, claimed: Boolean(connectionId) })), matchScore: room.matchScore, duelNumber: room.duelNumber, duel: room.duel, tools: { ...emptyTools(), ...(room.tools || {}) }, recovered: Boolean(room.recovered) }); }
  subscribe(code, callback) { const key = String(code).toUpperCase(); const set = this.listeners.get(key) || new Set(); set.add(callback); this.listeners.set(key, set); return () => { set.delete(callback); if (!set.size) this.listeners.delete(key); }; }
  broadcast(room) { const snapshot = this.snapshot(room); for (const listener of this.listeners.get(room.code) || []) listener(snapshot); }
  create(connectionId, { name: hostName, matchFormat = "best_of_three" } = {}) {
    const connection = this.connections.get(connectionId); if (!connection) throw Object.assign(new Error("Reconnect and try again."), { status: 401, code: "CONNECTION_EXPIRED" });
    if (!["single_duel", "best_of_three"].includes(matchFormat)) throw Object.assign(new Error("Choose a valid Match format."), { status: 400, code: "INVALID_INPUT" });
    let code; do { code = roomCode(); } while (this.rooms.has(code));
    const seatToken = id(); const createdAt = this.now();
    const room = { code, version: 1, createdAt, matchFormat, recovered: false, duelists: [{ seatId: 0, name: name(hostName, "Duelist 1"), connectionId, reclaimTokenHash: tokenHash(seatToken) }, { seatId: 1, name: "Duelist 2", connectionId: null, reclaimTokenHash: null }], matchScore: [0, 0], duelNumber: 1, duel: this.blankDuel(0), tools: emptyTools() };
    this.rooms.set(code, room); connection.seatKey = `${code}:0`; this.persist(); return { snapshot: this.snapshot(room), seatId: 0, reclaimToken: seatToken };
  }
  claim(code, connectionId, { seatId, name: displayName, reclaimToken } = {}) {
    const room = this.room(code); const connection = this.connections.get(connectionId); if (!connection) throw Object.assign(new Error("Reconnect and try again."), { status: 401, code: "CONNECTION_EXPIRED" });
    if (![0, 1].includes(seatId)) throw Object.assign(new Error("Choose an open Duelist seat."), { status: 400, code: "INVALID_INPUT" }); const duelist = room.duelists[seatId];
    const reclaiming = duelist.connectionId && duelist.connectionId !== connectionId;
    if (duelist.reclaimTokenHash && duelist.reclaimTokenHash !== tokenHash(reclaimToken || "")) throw Object.assign(new Error(reclaiming ? "That seat is already claimed on another phone." : "This saved seat needs its original phone to reclaim it."), { status: reclaiming ? 409 : 403, code: "RECLAIM_REQUIRED" });
    if (reclaiming) { const priorConnection = this.connections.get(duelist.connectionId); if (priorConnection) priorConnection.seatKey = null; }
    const token = duelist.reclaimTokenHash ? reclaimToken : id(); duelist.connectionId = connectionId; duelist.reclaimTokenHash = tokenHash(token); duelist.name = name(displayName, `Duelist ${seatId + 1}`); connection.seatKey = `${room.code}:${seatId}`; room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room), seatId, reclaimToken: token };
  }
  blankDuel(firstSeatId) { return { lifePoints: [8000, 8000], activeSeatId: firstSeatId, turnNumber: 1, phaseIndex: 0, firstTurn: true, phaseHistory: [], lifePointLog: [], outcome: null, priorLoserSeatId: null }; }
  bothClaimed(room) { return room.duelists.every(item => item.connectionId); }
  adjust(code, connectionId, { delta, note = "" } = {}) {
    const room = this.room(code); const seatId = this.owner(room, connectionId); if (room.duel.outcome) throw Object.assign(new Error("Record the next Duel before changing LP."), { status: 409, code: "DUEL_COMPLETE" });
    const amount = Number(delta); if (!Number.isInteger(amount) || amount === 0 || Math.abs(amount) > 99999) throw Object.assign(new Error("Enter a whole LP change."), { status: 400, code: "INVALID_INPUT" });
    const after = room.duel.lifePoints[seatId] + amount; if (after < -99999 || after > 999999) throw Object.assign(new Error("That LP total is outside the supported range."), { status: 400, code: "INVALID_INPUT" });
    room.duel.lifePoints[seatId] = after; room.duel.lifePointLog.push({ id: id(), kind: "adjustment", seatId, delta: amount, after, note: String(note).trim().slice(0, 80), at: this.now() }); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) };
  }
  correct(code, connectionId, { entryId, delta, note = "" } = {}) {
    const room = this.room(code); const seatId = this.owner(room, connectionId); const original = room.duel.lifePointLog.find(entry => entry.id === entryId && entry.seatId === seatId); if (!original) throw Object.assign(new Error("Choose one of your own LP entries to correct."), { status: 400, code: "INVALID_INPUT" });
    const amount = Number(delta); if (!Number.isInteger(amount) || amount === 0) throw Object.assign(new Error("Enter a whole correction amount."), { status: 400, code: "INVALID_INPUT" }); const after = room.duel.lifePoints[seatId] + amount; room.duel.lifePoints[seatId] = after;
    room.duel.lifePointLog.push({ id: id(), kind: "correction", correctsEntryId: entryId, seatId, delta: amount, after, note: String(note).trim().slice(0, 80), at: this.now() }); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) };
  }
  advancePhase(code, connectionId) { const room = this.room(code); const seatId = this.owner(room, connectionId); if (!this.bothClaimed(room)) throw Object.assign(new Error("Wait for both Duelists to join."), { status: 409, code: "WAITING_FOR_DUELIST" }); if (seatId !== room.duel.activeSeatId) throw Object.assign(new Error("Only the active Duelist advances the turn."), { status: 403, code: "NOT_ACTIVE_DUELIST" });
    const from = { activeSeatId: room.duel.activeSeatId, turnNumber: room.duel.turnNumber, phaseIndex: room.duel.phaseIndex, firstTurn: room.duel.firstTurn }; room.duel.phaseHistory.push(from);
    if (room.duel.phaseIndex < PHASES.length - 1) room.duel.phaseIndex++; else { room.duel.phaseIndex = 0; room.duel.activeSeatId = seatId === 0 ? 1 : 0; room.duel.turnNumber++; room.duel.firstTurn = false; }
    room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) };
  }
  undoPhase(code, connectionId) { const room = this.room(code); const seatId = this.owner(room, connectionId); const prior = room.duel.phaseHistory.at(-1); if (!prior || seatId !== room.duel.activeSeatId && seatId !== prior.activeSeatId) throw Object.assign(new Error("There is no phase advance you can undo."), { status: 409, code: "NOT_UNDOABLE" }); Object.assign(room.duel, prior); room.duel.phaseHistory.pop(); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  declareOutcome(code, connectionId, { winnerSeatId, type = "win" } = {}) { const room = this.room(code); this.owner(room, connectionId); if (![0, 1].includes(winnerSeatId) || !["win", "concession"].includes(type)) throw Object.assign(new Error("Choose a Duel winner and outcome."), { status: 400, code: "INVALID_INPUT" }); room.duel.outcome = { winnerSeatId, type, declaredAt: this.now() }; room.matchScore[winnerSeatId]++; room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  nextDuel(code, connectionId, { firstSeatId } = {}) { const room = this.room(code); this.owner(room, connectionId); if (!room.duel.outcome) throw Object.assign(new Error("Declare this Duel's outcome first."), { status: 409, code: "OUTCOME_REQUIRED" }); if (room.matchFormat === "best_of_three" && Math.max(...room.matchScore) >= 2) throw Object.assign(new Error("This Match is complete."), { status: 409, code: "MATCH_COMPLETE" }); const loser = room.duel.outcome.winnerSeatId === 0 ? 1 : 0; if (![0, 1].includes(firstSeatId)) throw Object.assign(new Error("The previous Duel loser chooses first or second."), { status: 400, code: "INVALID_INPUT" }); room.duelNumber++; room.duel = this.blankDuel(firstSeatId); room.duel.priorLoserSeatId = loser; room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  tools(room) { room.tools = { ...emptyTools(), ...(room.tools || {}) }; return room.tools; }
  randomize(code, connectionId, { sides = 2 } = {}) { const room = this.room(code); const seatId = this.owner(room, connectionId); const die = Number(sides); if (![2, 6, 20].includes(die)) throw Object.assign(new Error("Choose coin, d6, or d20."), { status: 400, code: "INVALID_INPUT" }); const tools = this.tools(room); const value = 1 + (randomBytes(1)[0] % die); tools.randomHistory.unshift({ id: id(), seatId, sides: die, value, at: this.now() }); tools.randomHistory = tools.randomHistory.slice(0, 8); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  addSharedNote(code, connectionId, { text } = {}) { const room = this.room(code); const seatId = this.owner(room, connectionId); const clean = String(text || "").trim().slice(0, 160); if (!clean) throw Object.assign(new Error("Enter a table note."), { status: 400, code: "INVALID_INPUT" }); const tools = this.tools(room); tools.notes.unshift({ id: id(), seatId, text: clean, at: this.now() }); tools.notes = tools.notes.slice(0, 12); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  addCounter(code, connectionId, { label, value = 0 } = {}) { const room = this.room(code); const seatId = this.owner(room, connectionId); const clean = String(label || "").trim().slice(0, 32); const amount = Number(value); if (!clean || !Number.isInteger(amount) || Math.abs(amount) > 999) throw Object.assign(new Error("Enter a counter name and a whole value from -999 to 999."), { status: 400, code: "INVALID_INPUT" }); const tools = this.tools(room); if (tools.counters.length >= 12) throw Object.assign(new Error("This Duel already has 12 shared counters."), { status: 409, code: "COUNTER_LIMIT" }); tools.counters.unshift({ id: id(), seatId, label: clean, value: amount }); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  addToken(code, connectionId, { name: tokenName, atk = 0, def: defense = 0, level = 0 } = {}) { const room = this.room(code); const seatId = this.owner(room, connectionId); const clean = String(tokenName || "").trim().slice(0, 32); const values = [atk, defense, level].map(Number); if (!clean || !values.every(Number.isInteger) || values[0] < 0 || values[0] > 99999 || values[1] < 0 || values[1] > 99999 || values[2] < 0 || values[2] > 13) throw Object.assign(new Error("Enter a Token name, ATK/DEF from 0 to 99,999, and Level 0 to 13."), { status: 400, code: "INVALID_INPUT" }); const tools = this.tools(room); if (tools.tokens.length >= 8) throw Object.assign(new Error("This Duel already has 8 shared Token notes."), { status: 409, code: "TOKEN_LIMIT" }); tools.tokens.unshift({ id: id(), seatId, name: clean, atk: values[0], def: values[1], level: values[2] }); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
  removeToolItem(code, connectionId, { type, itemId } = {}) { const room = this.room(code); const seatId = this.owner(room, connectionId); if (!['counter', 'token'].includes(type)) throw Object.assign(new Error("Choose a removable table item."), { status: 400, code: "INVALID_INPUT" }); const items = this.tools(room)[type === 'counter' ? 'counters' : 'tokens']; const index = items.findIndex(item => item.id === itemId && item.seatId === seatId); if (index < 0) throw Object.assign(new Error("You can remove only your own table items."), { status: 403, code: "NOT_OWNER" }); items.splice(index, 1); room.version++; this.persist(); this.broadcast(room); return { snapshot: this.snapshot(room) }; }
}
